import type { EngineInterface, Register } from 'claude-code'
import {
  CI_GIVE_UP_MS, CI_POLL_MS, DOCUMENTED_TEST_DSN, MUTATION_TIMEOUT_MS, MUTATION_TOOL, MUTATION_TOOL_SPEC,
  TEST_DATABASE_NOTE, ciMessage, ciVerdict, dsnFromEnvFile, mutationVerdict, replaceOnce, withTestDatabase,
  type MutationInput,
} from './assist'

const ROLES = ['skillhub-writer', 'skillhub-verify', 'skillhub-mutation']
const FAMILIES = ['fable', 'opus', 'sonnet', 'haiku']
const RUNTIME_IMAGE = 'infra/images/runtime-agent-sdk'
const DOMAIN_MEMORY = 'docs/domain-memory'
const AGENT_CACHES = ['.agents/', '.codex/']
const ALLOW_HINT = 'If the owner agrees, ask them to type /guard-allow, then retry once.'
const GENERATED_BANNER_LINES = 15

const AT_COMMAND = String.raw`(?:^|[;&|(\n]|\$\()\s*(?:[A-Za-z_]\w*=\S*\s+)*(?:rtk\s+(?:proxy\s+)?)?`
const ARG = String.raw`(?:"[^"]*"|'[^']*'|\S+)`
const GIT = String.raw`${AT_COMMAND}git(?:\s+(?:-C\s+${ARG}|-c\s+${ARG}|--[\w-]+(?:=${ARG})?))*\s+`
const NPM_FLAGS = String.raw`(?:\s+-{1,2}[\w-]+(?:[ =]${ARG})?)*`

const at = (pattern: string) => new RegExp(AT_COMMAND + pattern)

const SUBAGENT_RULES: [RegExp, string][] = [
  [at(String.raw`task\s+dev:model\b`), 'may not start the paid model stack (AGENTS.md 開發自動化 2)'],
  [at(String.raw`docker[\s-]compose\b[^;&|\n]*--profile\s+model\b[^;&|\n]*\sup\b`),
    'may not start the paid model stack (AGENTS.md 開發自動化 2)'],
  [new RegExp(GIT + String.raw`(?:commit|push|pull|rebase|merge|cherry-pick|revert|am|apply|add|rm|mv|switch|checkout|restore|reset|stash|clean|update-ref|worktree\s+(?:add|remove|move|prune)|branch\s+-[dDmMfc])\b`),
    'may not write to Git; the dispatcher stages and commits (AGENTS.md 開發自動化 3)'],
  [at(String.raw`(?:npm|pnpm|yarn)${NPM_FLAGS}\s+(?:install|i|ci|add|update|uninstall|remove)\b`),
    'may not install or update packages (AGENTS.md 開發自動化 3)'],
  [at(String.raw`go(?:\s+-C\s+${ARG})?\s+(?:get|install|mod\s+tidy)\b`),
    'may not install or update packages (AGENTS.md 開發自動化 3)'],
  [at(String.raw`(?:uv\s+(?:add|remove|sync|lock|pip\s+install)|pip3?\s+install)\b`),
    'may not install or update packages (AGENTS.md 開發自動化 3)'],
  [at(String.raw`docker[\s-]compose\b[^;&|\n]*\sdown\b`), 'may not run Compose down (AGENTS.md 開發自動化 3)'],
  [at(String.raw`(?:npx\s+)?(?:prettier\b[^;&|\n]*--write\s+\.|gofmt\s+-\w*w\w*\s+\.|ruff\s+format\s+\.)(?:\s|$)`),
    'may not run a repo-wide formatter (AGENTS.md 開發自動化 3)'],
  [at(String.raw`(?:npm${NPM_FLAGS}\s+run\s+format|task\s+format)(?:\s|$)`),
    'may not run a repo-wide formatter (AGENTS.md 開發自動化 3)'],
  [at(String.raw`task\s+gen(?::(?!check\b)[\w-]+)?(?:\s|$)`),
    'may not regenerate generated files; the dispatcher serialises it (AGENTS.md 開發自動化 5)'],
  [/\b(?:run\s+\.|devctl)\s+agent-sync\b/, 'may not run agent-sync; only the single writer does (AGENTS.md 開發自動化 3)'],
]

const GIT_PUSH = new RegExp(GIT + String.raw`push\b`)
const GIT_COMMIT = new RegExp(GIT + String.raw`commit\b`)
const SIGNED = /\s(?:-S\S*|--gpg-sign\S*)(?=\s|$)/
const GENERATED_BANNER = /^\s*(?:\/\/|#|\/?\*|--)\s*.*(?:code generated|generated - do not edit|auto generated by|generated by datamodel-codegen)/i
const TEST_RUN = at(String.raw`(?:go(?:\s+-C\s+${ARG})?\s+test|npm${NPM_FLAGS}\s+(?:test|run\s+test\S*)|npx\s+(?:vitest|playwright)|uv\s+run\s+pytest|pytest|task\s+test)\b`)

const familyOf = (model: string | undefined) =>
  FAMILIES.find(family => (model ?? '').toLowerCase().includes(family))

const normalize = (path: string) => path.replace(/\\/g, '/').toLowerCase()

const directoryOf = (path: string) => {
  const slash = Math.max(path.lastIndexOf('/'), path.lastIndexOf('\\'))
  return slash > 0 ? path.slice(0, slash) : '.'
}

export const spawnProblem = (
  model: string | undefined, subagentType: string, parentModel: string, fork: boolean,
): string | undefined => {
  if (fork) {
    return 'a fork always runs on the dispatcher\'s flagship model; dispatch a named agent with a lower model ' +
      '(AGENTS.md 開發自動化 3)'
  }
  if (model === undefined && !ROLES.includes(subagentType)) {
    return `name a model for this subagent or use one of ${ROLES.join(', ')}; ` +
      'an unnamed model inherits the dispatcher\'s flagship model (AGENTS.md 開發自動化 3)'
  }
  const family = familyOf(model)
  if (family === 'fable' || (family !== undefined && family === familyOf(parentModel))) {
    return `model ${model} is the dispatcher's own tier; subagents start from the lowest tier ` +
      'that can finish the task (AGENTS.md 開發自動化 3)'
  }
  return undefined
}

export const subagentCommandProblem = (command: string): string | undefined =>
  SUBAGENT_RULES.find(([pattern]) => pattern.test(command))?.[1]

export const isGeneratedHeader = (text: string): boolean =>
  text.split('\n', GENERATED_BANNER_LINES).some(line => GENERATED_BANNER.test(line))

export const isAgentCache = (path: string, root: string): boolean => {
  const prefix = normalize(root).replace(/\/$/, '') + '/'
  const target = normalize(path)
  return AGENT_CACHES.some(cache => target.startsWith(prefix + cache))
}

export const needsSignature = (command: string): boolean =>
  GIT_COMMIT.test(command) && !SIGNED.test(command)

const porcelainPaths = (porcelain: string): string[] => {
  const paths: string[] = []
  const fields = porcelain.split('\0')
  for (let i = 0; i < fields.length; i++) {
    const field = fields[i] ?? ''
    if (field.length < 4) continue
    paths.push(field.slice(3))
    if (field[0] === 'R' || field[0] === 'C') i++
  }
  return paths
}

export const attributedToCommand = (before: string, after: string): string[] => {
  const was = new Set(porcelainPaths(before))
  return porcelainPaths(after).filter(path => !was.has(path))
}

async function touched($: EngineInterface): Promise<string[]> {
  return (await $.state.get({ plugin: 'skillhub-guards', key: 'touched' })).value ?? []
}

async function remember($: EngineInterface, paths: string[]) {
  const list = await touched($)
  const fresh = paths.map(normalize).filter(path => !list.includes(path))
  if (fresh.length > 0) await $.state.set({ plugin: 'skillhub-guards', key: 'touched' }, [...list, ...fresh])
}

async function consumeAllowance($: EngineInterface, action: string): Promise<boolean> {
  const allowance = (await $.state.get({ plugin: 'skillhub-guards', key: 'allowance' })).value
  if (allowance !== action) return false
  await $.state.set({ plugin: 'skillhub-guards', key: 'allowance' }, null)
  return true
}

async function refuse($: EngineInterface, action: string, reason: string) {
  await $.state.set({ plugin: 'skillhub-guards', key: 'lastDenied' }, action)
  return { deny: `skillhub-guards: ${reason} ${ALLOW_HINT}` }
}

async function status($: EngineInterface, root: string): Promise<string | undefined> {
  const result = await $.process.run(['git', '-C', root, 'status', '--porcelain', '-z'])
  return result.exitCode === 0 ? result.stdout : undefined
}

async function readHeader($: EngineInterface, path: string): Promise<string> {
  try {
    return (await $.fs.read(path)).slice(0, 4096)
  } catch {
    return ''
  }
}

async function testDsn($: EngineInterface, root: string): Promise<string> {
  try {
    return dsnFromEnvFile(await $.fs.read(`${root}/.env`)) ?? DOCUMENTED_TEST_DSN
  } catch {
    return DOCUMENTED_TEST_DSN
  }
}

async function pollCI($: EngineInterface) {
  const watch = (await $.state.get({ plugin: 'skillhub-guards', key: 'ciWatch' })).value
  if (!watch) return
  if (Date.now() - watch.since > CI_GIVE_UP_MS) {
    $.ui.status(`CI ${watch.sha.slice(0, 8)}: still not finished after an hour`)
    await $.state.set({ plugin: 'skillhub-guards', key: 'ciWatch' }, null)
    return
  }
  const root = await $.session.root()
  const run = await $.process.run(['go', '-C', `${root}/tools/devctl`, 'run', '.', 'ci-status', watch.sha],
    { timeoutMs: 120_000 })
  const output = `${run.stdout}\n${run.stderr}`
  const verdict = ciVerdict(output)
  if (verdict === undefined || verdict === 'pending') {
    $.ui.status(`CI ${watch.sha.slice(0, 8)}: running`)
    return
  }
  await $.state.set({ plugin: 'skillhub-guards', key: 'ciWatch' }, null)
  const text = ciMessage(watch.sha, verdict, output)
  $.ui.status(text)
  $.ui.toast(text, { timeoutMs: 15_000 })
}

export const register: Register = on => {
  on('session.start', async ($, e, next) => {
    await $.command.register({
      name: 'guard-allow',
      description: 'Let the action skillhub-guards last refused through, once',
    })
    await $.tool.register(MUTATION_TOOL_SPEC)
    $.clock.every(CI_POLL_MS, () => { void pollCI($) })
    return next(e)
  })

  on('command.run', { command: 'guard-allow' }, async ($, e) => {
    if (e.origin.kind !== 'composer' && e.origin.kind !== 'bridge') {
      return { text: 'skillhub-guards: only a person typing /guard-allow can grant it.' }
    }
    const lastDenied = (await $.state.get({ plugin: 'skillhub-guards', key: 'lastDenied' })).value
    if (!lastDenied) return { text: 'skillhub-guards: nothing has been refused yet.' }
    await $.state.set({ plugin: 'skillhub-guards', key: 'allowance' }, lastDenied)
    return { text: `skillhub-guards: the next attempt at ${lastDenied} goes through, once.` }
  })

  on('agent.spawn', ($, e, next) => {
    const problem = spawnProblem(e.model, e.subagentType, e.parentModel, e.fork)
    return problem ? { deny: `skillhub-guards: ${problem}` } : next(e)
  })

  on('tool.call', { tool: 'Bash' }, async ($, e, next) => {
    const problem = e.agentId !== undefined ? subagentCommandProblem(e.command) : undefined
    if (problem) return { deny: `skillhub-guards: a subagent ${problem}.` }
    const root = await $.session.root()

    if (GIT_PUSH.test(e.command)) {
      const head = (await $.process.run(['git', '-C', root, 'rev-parse', 'HEAD'])).stdout.trim()
      const upstream = await $.process.run(['git', '-C', root, 'rev-parse', '--verify', '--quiet', '@{u}'])
      const base = upstream.exitCode === 0 ? '@{u}' : 'origin/main'
      const changed = await $.process.run(['git', '-C', root, 'diff', '--name-only', `${base}..HEAD`, '--', RUNTIME_IMAGE])
      const action = `push of ${head.slice(0, 8)} touching ${RUNTIME_IMAGE}`
      if (changed.stdout.trim() !== '' && !(await consumeAllowance($, action))) {
        return refuse($, action,
          'this push publishes a new runtime image tag, which cannot be withdrawn; ask the owner first ' +
          '(.claude/rules/tests.md).')
      }
    }

    if (needsSignature(e.command)) {
      const staged = await $.process.run(['git', '-C', root, 'diff', '--cached', '--name-only', '--', DOMAIN_MEMORY])
      const action = `unsigned commit touching ${DOMAIN_MEMORY}`
      if (staged.stdout.trim() !== '' && !(await consumeAllowance($, action))) {
        return refuse($, action,
          `commits touching ${DOMAIN_MEMORY} must be signed (git commit -S); the server rejects an unsigned one ` +
          'at push, and amend and reset are not allowed to repair it.')
      }
    }

    const rewritten = withTestDatabase(e.command, await testDsn($, root))
    if (rewritten !== undefined) {
      const result = await next({ ...e, command: rewritten })
      const shell = result.result as { stdout?: unknown } | undefined
      if (result.deny !== undefined || typeof shell?.stdout !== 'string') return result
      return { ...result, result: { ...shell, stdout: TEST_DATABASE_NOTE + shell.stdout } }
    }

    const watched = TEST_RUN.test(e.command) ? undefined : await status($, root)
    const result = await next(e)
    const after = watched === undefined ? undefined : await status($, root)
    if (watched !== undefined && after !== undefined) {
      await remember($, attributedToCommand(watched, after).map(path => `${root}/${path}`))
    }
    if (e.agentId === undefined && GIT_PUSH.test(e.command) && result.deny === undefined && result.isError !== true) {
      const sha = (await $.process.run(['git', '-C', root, 'rev-parse', 'HEAD'])).stdout.trim()
      await $.state.set({ plugin: 'skillhub-guards', key: 'ciWatch' }, { sha, since: Date.now() })
      $.ui.status(`CI ${sha.slice(0, 8)}: waiting`)
    }
    return result
  })

  on('tool.call', { tool: `mcp__skillhub-guards__${MUTATION_TOOL}` }, async ($, e) => {
    const input = e.input as MutationInput
    const root = await $.session.root()
    const path = /^([a-zA-Z]:|\/)/.test(input.file) ? input.file : `${root}/${input.file}`
    const original = await $.fs.read(path)
    const mutated = replaceOnce(original, input.find, input.replace)
    if (typeof mutated !== 'string') return { result: mutated.problem, isError: true as const }

    await $.fs.write(path, mutated)
    let run
    try {
      run = await $.process.run(input.argv, {
        cwd: input.cwd ? `${root}/${input.cwd}` : root, env: input.env, timeoutMs: MUTATION_TIMEOUT_MS,
      })
    } finally {
      await $.fs.write(path, original)
    }
    const restored = (await $.fs.read(path)) === original
    const { verdict, summary } = mutationVerdict(run.exitCode, `${run.stdout}\n${run.stderr}`)
    if (!restored) {
      return { result: `RESTORE FAILED: ${path} differs from before; fix it now\n${verdict}\n\n${summary}`, isError: true as const }
    }
    return { result: `${verdict}\nfile restored byte for byte\n\n${summary}` }
  })

  on('tool.call', { tool: ['Edit', 'Write'] }, async ($, e, next) => {
    if (e.tool !== 'Edit' && e.tool !== 'Write') return next(e)
    const path = e.file_path
    if (isAgentCache(path, await $.session.root())) {
      return { deny: `skillhub-guards: ${path} is a generated agent cache; edit .claude/agents or .claude/skills ` +
        'and run agent-sync (AGENTS.md 開發自動化 3).' }
    }
    if (isGeneratedHeader(await readHeader($, path))) {
      return { deny: `skillhub-guards: ${path} declares itself generated; change its source and regenerate with ` +
        'task gen:sql or task gen:openapi (AGENTS.md 開發自動化 5).' }
    }
    if (!(await touched($)).includes(normalize(path))) {
      const dirty = await $.process.run(['git', '-C', directoryOf(path), 'status', '--porcelain', '--', path])
      const action = `edit of ${path}`
      if (dirty.exitCode === 0 && dirty.stdout.trim() !== '' && !(await consumeAllowance($, action))) {
        return refuse($, action,
          `${path} has uncommitted changes this session did not make; keep them and report ` +
          '(AGENTS.md 開發自動化 3).')
      }
    }
    const result = await next(e)
    if (result.deny === undefined && result.isError !== true) await remember($, [path])
    return result
  })
}
