export const ENTRY_KIND: Record<string, string> = {
  debit: "扣點",
  grant: "授予",
  topup: "儲值",
  adjustment: "更正",
};

export const ACTION_LABEL: Record<string, string> = {
  "skill.access_restrict": "設定受限展示",
  "skill.access_unrestrict": "解除受限展示",
  "skill.redistribution_set": "再散布判定",
  "skill.curation_set": "精選層級",
  "skill.takedown": "下架",
  "credit.grant": "授予點數",
  "dispatch.halted": "停止派送",
  "dispatch.resumed": "恢復派送",
  "account.lookup": "查詢帳號",
  "credit.lookup": "查詢點數",
  "platform_agent.enabled": "啟用平台 Agent",
  "platform_agent.disabled": "停用平台 Agent",
  "platform_agent.brake_engaged": "拉下 Agent 煞車",
  "platform_agent.brake_released": "放開 Agent 煞車",
  "platform_agent.spend_cap_set": "調整 Agent 每日花費上限",
  "evaluation_settings.set": "調整評估設定",
  "run_settings.set": "調整試跑設定",
  "platform_agent_finding.opened": "開了一筆待辦",
  "platform_agent_finding.reopened": "重新打開待辦",
  "platform_agent_finding.recovered": "待辦自行恢復",
  "platform_agent_finding.acknowledged": "接手待辦",
  "platform_agent_finding.resolved": "解決待辦",
  "platform_agent_finding.dismissed": "忽略待辦",
  "platform_agent_proposal.proposed": "Agent 提出提案",
  "platform_agent_proposal.approved": "核准提案",
  "platform_agent_proposal.rejected": "駁回提案",
  "platform_agent_proposal.expired": "提案逾期作廢",
  "platform_agent_proposal.started": "提案開始執行",
  "platform_agent_proposal.requeued": "工作正在執行，提案退回待執行",
  "platform_agent_proposal.succeeded": "提案執行完成",
  "platform_agent_proposal.failed": "提案執行失敗",
};

export const COST_KIND: Record<string, string> = {
  creation_step: "創作步驟",
  creation_session: "創作會話",
  search_embedding: "搜尋向量",
  search_intent: "搜尋意圖分析",
  platform_agent: "平台 Agent",
  index_enrich: "索引增強",
  review: "評審",
  suggestion: "改善建議",
  generate: "單次生成",
  run: "試跑",
  match_reasons: "搜尋理由",
};
