import type { On } from 'claude-code'
import { expect, test } from 'claude-code/testing'
import {
  attributedToCommand, isAgentCache, isGeneratedHeader, needsSignature, spawnProblem, subagentCommandProblem,
} from '../hooks/register'

const PARENT = 'claude-opus-5-5'

test('a subagent with no model and no role is refused', () => {
  expect(spawnProblem(undefined, 'general-purpose', PARENT, false)).toMatch(/name a model/)
})

test('a repository role without a model is allowed, its frontmatter pins one', () => {
  expect(spawnProblem(undefined, 'skillhub-writer', PARENT, false)).toBeUndefined()
})

test('a subagent on the dispatcher\'s own family is refused', () => {
  expect(spawnProblem('opus', 'general-purpose', PARENT, false)).toMatch(/dispatcher's own tier/)
})

test('a subagent one tier below the dispatcher is allowed', () => {
  expect(spawnProblem('sonnet', 'general-purpose', PARENT, false)).toBeUndefined()
})

test('fable is refused even under a fable-less dispatcher', () => {
  expect(spawnProblem('fable', 'general-purpose', 'claude-sonnet-5-5', false)).toMatch(/dispatcher's own tier/)
})

test('opus is allowed when the dispatcher is fable', () => {
  expect(spawnProblem('opus', 'Explore', 'claude-fable-5-1', false)).toBeUndefined()
})

test('a fork is refused whatever model it names, it always runs on the dispatcher\'s', () => {
  expect(spawnProblem('haiku', 'fork', PARENT, true)).toMatch(/fork/)
})

const refusedForSubagents: [string, string][] = [
  ['task dev:model', 'paid'],
  ['docker compose --env-file .env --profile model -f infra/compose/docker-compose.yml up -d', 'paid'],
  ['git commit -m "x"', 'Git'],
  ['cd "c:/repo" && git add apps/web/a.ts', 'Git'],
  ['git -C "c:/a b" push', 'Git'],
  ['rtk git rebase origin/main', 'Git'],
  ['GIT_EDITOR=true git merge main', 'Git'],
  ['git apply /tmp/p.patch', 'Git'],
  ['git worktree remove x', 'Git'],
  ['git branch -D topic', 'Git'],
  ['npm --prefix apps/web install', 'install'],
  ['npm ci', 'install'],
  ['go get example.com/m@v1', 'install'],
  ['go -C apps/platform mod tidy', 'install'],
  ['uv add httpx', 'install'],
  ['pip install x', 'install'],
  ['docker compose -f infra/compose/docker-compose.yml down', 'Compose down'],
  ['npx prettier --write .', 'formatter'],
  ['gofmt -w .', 'formatter'],
  ['npm run format', 'formatter'],
  ['task gen:openapi', 'generated'],
  ['task gen', 'generated'],
  ['go -C tools/devctl run . agent-sync', 'agent-sync'],
]

for (const [command, reason] of refusedForSubagents) {
  test(`a subagent running "${command}" is refused for ${reason}`, () => {
    expect(subagentCommandProblem(command)).toContain(reason)
  })
}

const allowedForSubagents = [
  'git status --short',
  'git diff HEAD~1 -- apps/web',
  'git log --oneline --grep commit',
  'git worktree list',
  'git branch -a',
  'grep -n "git commit" docs/development/automation.md',
  'npm run format:check',
  'npm --prefix apps/web run typecheck',
  'task gen:check',
  'gofmt -l apps/platform',
  'npx prettier --write apps/web/src/a.tsx',
  'go test -count=1 ./internal/...',
  'docker compose ps',
  'task dev',
]

for (const command of allowedForSubagents) {
  test(`a subagent running "${command}" is allowed`, () => {
    expect(subagentCommandProblem(command)).toBeUndefined()
  })
}

test('a Go file opening with the sqlc banner is generated', () => {
  expect(isGeneratedHeader('// Code generated by sqlc. DO NOT EDIT.\n// versions:\n')).toBe(true)
})

test('an OpenAPI Generator class note inside its header comment is generated', () => {
  expect(isGeneratedHeader('/* tslint:disable */\n/**\n * NOTE: This class is auto generated by OpenAPI Generator\n */\n')).toBe(true)
})

test('a datamodel-codegen banner is generated', () => {
  expect(isGeneratedHeader('# generated by datamodel-codegen:\n#   filename:  llm-internal.yaml\n')).toBe(true)
})

test('a banner on the fifteenth line still counts, on the sixteenth it does not', () => {
  const blank = (n: number) => '\n'.repeat(n)
  expect(isGeneratedHeader(`${blank(14)}// Code generated by ogen, DO NOT EDIT.\n`)).toBe(true)
  expect(isGeneratedHeader(`${blank(15)}// Code generated by ogen, DO NOT EDIT.\n`)).toBe(false)
})

test('a README that tells people not to edit a generated folder is not itself generated', () => {
  expect(isGeneratedHeader('# api-client-ts\n\n- `src/generated/**` is generated; **do not edit it**.\n')).toBe(false)
})

test('a test that writes a generated banner inside a string is not generated', () => {
  expect(isGeneratedHeader('package main\n\n\twriteGoFile(t, root, "x.go", `// Code generated by sqlc. DO NOT EDIT.\n')).toBe(false)
})

test('the agent caches under the project root are recognised on either slash and any case', () => {
  expect(isAgentCache('C:\\Repo\\.agents\\skills\\x\\SKILL.md', 'c:/repo')).toBe(true)
  expect(isAgentCache('c:/repo/.codex/agents/a.toml', 'C:\\Repo')).toBe(true)
})

test('the editable sources of those caches are not caches', () => {
  expect(isAgentCache('c:/repo/.claude/skills/x/SKILL.md', 'c:/repo')).toBe(false)
  expect(isAgentCache('c:/repo/docs/.agents-notes.md', 'c:/repo')).toBe(false)
})

test('a commit without -S needs a signature check', () => {
  expect(needsSignature('git commit -q -F - <<\'EOF\'')).toBe(true)
  expect(needsSignature('cd x && git -C y commit -m "a"')).toBe(true)
})

test('a signed commit, or a command that is not a commit, does not', () => {
  expect(needsSignature('git commit -S -m "a"')).toBe(false)
  expect(needsSignature('git commit --gpg-sign -m "a"')).toBe(false)
  expect(needsSignature('git log --grep commit')).toBe(false)
})

test('only entries that changed during the command are attributed to it', () => {
  const before = ' M apps/a.ts\0?? other-session.txt\0'
  const after = ' M apps/a.ts\0?? other-session.txt\0 M apps/b.ts\0?? new.txt\0R  moved.ts\0was.ts\0'
  expect(attributedToCommand(before, after)).toEqual(['apps/b.ts', 'new.txt', 'moved.ts'])
})

const ROOT = 'c:/repo'

const world = (
  on: On, git: (argv: string[]) => string, header = '',
  ran: (tool: string) => void = () => {},
) => {
  on('session.root', () => ({ value: ROOT }))
  on('process.run', (_, e) => ({
    value: { exitCode: 0, stdout: git([...e.argv]), stderr: '', isStdoutTruncated: false, isStderrTruncated: false },
  }))
  on('fs.read', () => ({ value: header }))
  on('tool.call', (_, e) => { ran(e.tool); return { result: 'ran' } })
}

test('the Bash hook refuses a subagent\'s commit before it runs', async ($, on) => {
  world(on, () => '')
  const fromASubagent = { tool: 'Bash' as const, command: 'git commit -m x', agentId: 'agent-1' }
  const result = await $.tool.call(fromASubagent)
  expect(result.deny).toMatch(/may not write to Git/)
})

test('the Bash hook refuses a heredoc that writes backslashes into a code file', async ($, on) => {
  const ran: string[] = []
  world(on, () => '', '', tool => ran.push(tool))
  const result = await $.tool.call({ tool: 'Bash', command: "cat > /tmp/m.mjs <<'EOF'\nconst r = /\\d+/\nEOF" })
  expect(result.deny).toMatch(/write the file with the Write tool/)
  expect(ran).toEqual([])
})

test('the Edit hook refuses a file whose header declares it generated', async ($, on) => {
  world(on, () => '', '// Code generated by sqlc. DO NOT EDIT.\n')
  const result = await $.tool.call({ tool: 'Edit', file_path: `${ROOT}/gen/q.sql.go`, old_string: 'a', new_string: 'b' })
  expect(result.deny).toMatch(/declares itself generated/)
})

test('the Edit hook refuses a file another session left uncommitted', async ($, on) => {
  world(on, argv => argv.includes('--porcelain') ? ' M apps/b.ts\0' : '')
  const result = await $.tool.call({ tool: 'Edit', file_path: `${ROOT}/apps/b.ts`, old_string: 'a', new_string: 'b' })
  expect(result.deny).toMatch(/uncommitted changes this session did not make/)
})

test('a file this session\'s own command changed can then be edited', async ($, on) => {
  let applied = false
  const edited: string[] = []
  world(on, argv => {
    if (!argv.includes('--porcelain')) return ''
    return applied ? ' M apps/b.ts\0' : ''
  }, '', tool => { if (tool === 'Bash') applied = true; else edited.push(tool) })
  await $.tool.call({ tool: 'Bash', command: 'git apply /tmp/p.patch' })
  expect(applied).toBe(true)
  const result = await $.tool.call({ tool: 'Edit', file_path: `${ROOT}/apps/b.ts`, old_string: 'a', new_string: 'b' })
  expect(result.deny).toBeUndefined()
  expect(edited).toEqual(['Edit'])
})

test('a file another session had already changed is not attributed even if the command touched it again', () => {
  expect(attributedToCommand(' M apps/a.ts\0', ' M apps/a.ts\0')).toEqual([])
  expect(attributedToCommand(' M apps/a.ts\0', 'MM apps/a.ts\0')).toEqual([])
})
