package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestAutomationCheckNamesMissingDocTextUndescribedTasksAndMissingGeneratedMarkers(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	marker := filepath.Join("apps", "platform", "internal", "foundation", "persistence", "db", "gen", "db.go")
	for relative, contents := range map[string]string{
		"AGENTS.md": "nothing here\n",
		filepath.Join("docs", "development", "automation.md"): "nothing here\n",
		"Taskfile.yml": "tasks:\n  doctor:\n    cmds: [x]\n",
		marker:         "package gen\n",
	} {
		path := filepath.Join(root, relative)
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(contents), 0o600); err != nil {
			t.Fatal(err)
		}
	}
	var out strings.Builder
	if err := automationCheck(root, &out); err == nil {
		t.Fatal("an empty repository passed the automation contract")
	}
	for _, want := range []string{
		"FAIL AGENTS.md: missing \"task doctor\"\n",
		"FAIL Taskfile.yml: task doctor has no desc\n",
		"FAIL Taskfile.yml: missing discoverable task bootstrap\n",
		"FAIL " + marker + ": missing generated ownership marker \"Code generated by sqlc\"\n",
	} {
		if !strings.Contains(out.String(), want) {
			t.Errorf("output is missing %q", want)
		}
	}
}
