package main

import (
	"bufio"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

func automationCheck(root string, out io.Writer) error {
	requiredDocs := map[string][]string{
		"AGENTS.md": {
			"task doctor",
			"共享工作樹、單一 Writer",
			"generated files 禁止手改",
			"Go 側只生成 models，沒有 generated router 可以 mount",
			"docs/development/automation.md",
			"comment-budget",
		},
		filepath.Join("docs", "development", "automation.md"): {
			".devctl/**",
			"task gen:check",
			"SubAgent 預設唯讀",
			"不切 branch",

			"one-number:",
		},
	}
	var problems []string
	for relative, needles := range requiredDocs {
		data, err := os.ReadFile(filepath.Join(root, relative))
		if err != nil {
			problems = append(problems, fmt.Sprintf("%s: %v", relative, err))
			continue
		}
		text := string(data)
		for _, needle := range needles {
			if !strings.Contains(text, needle) {
				problems = append(problems, fmt.Sprintf("%s: missing %q", relative, needle))
			}
		}
	}

	tasks, err := taskDescriptions(filepath.Join(root, "Taskfile.yml"))
	if err != nil {
		return err
	}
	for name, description := range tasks {
		if strings.TrimSpace(description) == "" {
			problems = append(problems, fmt.Sprintf("Taskfile.yml: task %s has no desc", name))
		}
	}
	for _, name := range []string{"doctor", "bootstrap", "env:init", "gen", "gen:check", "agents:sync", "agents:check", "ci", "preflight", "ci:status"} {
		if _, ok := tasks[name]; !ok {
			problems = append(problems, fmt.Sprintf("Taskfile.yml: missing discoverable task %s", name))
		}
	}

	generatedMarkers := map[string]string{
		filepath.Join("apps", "platform", "internal", "foundation", "persistence", "db", "gen", "db.go"): "Code generated by sqlc",
		filepath.Join("apps", "platform", "internal", "entrypoint", "api", "gen", "oas_schemas_gen.go"):  "Code generated by ogen",
		filepath.Join("packages", "api-client-ts", "src", "generated", "runtime.ts"):                     "auto generated by OpenAPI Generator",
		filepath.Join("packages", "api-stub-py", "src", "skillhub_api_stub", "generated", "models.py"):   "generated by datamodel-codegen",
	}
	for relative, marker := range generatedMarkers {
		data, err := os.ReadFile(filepath.Join(root, relative))
		if err != nil {
			problems = append(problems, fmt.Sprintf("%s: %v", relative, err))
			continue
		}
		if !strings.Contains(string(data), marker) {
			problems = append(problems, fmt.Sprintf("%s: missing generated ownership marker %q", relative, marker))
		}
	}

	for _, checker := range documentCheckers() {
		problems = append(problems, checker.check(root)...)
	}

	if len(problems) > 0 {
		for _, problem := range problems {
			fmt.Fprintln(out, "FAIL", problem)
		}
		return errors.New("developer automation contract is incomplete")
	}
	fmt.Fprintf(out, "automation contract: %d tasks documented; agent and generated ownership checks passed\n", len(tasks))
	return nil
}

type namedChecker struct {
	name  string
	check func(root string) []string
}

func documentCheckers() []namedChecker {
	return []namedChecker{
		{"depguard-deny", depguardDenyProblems},
		{"service-construction", serviceConstructionProblems},
		{"identifier-order", identifierOrderProblems},
		{"one-number", sharedNumberProblems},
		{"sandbox-node-facts", sandboxNodeFactProblems},
		{"query-owner", queryOwnerProblems},
		{"query-scope", queryScopeProblems},
		{"sql-logic", sqlLogicProblems},
		{"context-map", contextMapProblems},
		{"doc-identifier", docIdentifierProblems},
		{"milestone-tally", milestoneTallyProblems},
		{"backlog-tally", backlogTallyProblems},
		{"baseline-tally", baselineTallyProblems},
		{"immutability-proof", immutabilityProofProblems},
		{"retention-floor", retentionFloorProblems},
		{"sdk-version", sdkVersionProblems},
		{"single-data-layer", secondDataLayerProblems},

		{"require-db-guard", func(root string) []string {
			if err := requireDBGuardCheck(root); err != nil {
				return []string{err.Error()}
			}
			return nil
		}},
		{"require-objstore-guard", requireObjstoreGuardProblems},
		{"isolation-level", isolationLevelProblems},
		{"domain-vocabulary", domainVocabularyProblems},
		{"run-status-sql", runStatusSQLProblems},
		{"route-table", routeTableProblems},
		{"requirement-refs", requirementRefProblems},
		{"purge-schedule", purgeScheduleProblems},
		{"timeout-budget", timeoutBudgetProblems},
		{"image-version", imageVersionProblems},
		{"embedding-dims", embeddingDimsProblems},
		{"goldenset-mirror", goldensetMirrorProblems},
		{"model-wire-boundary", modelWireBoundaryProblems},

		{"capability-table", capabilityTableProblems},
		{"env-declared", envDeclaredProblems},

		{"doc-links", docLinkProblems},
		{"doc-prose", docProseProblems},
		{"adr-citations", adrCitationProblems},

		{"dependency-policy", dependencyPolicyProblems},
		{"harness", harnessProblems},
		{"comment-budget", commentBudgetProblems},
		{"domain-memory", domainMemoryProblems},
	}
}

func taskDescriptions(path string) (map[string]string, error) {
	file, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer file.Close()

	tasks := map[string]string{}
	inTasks := false
	current := ""
	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := scanner.Text()
		trimmed := strings.TrimSpace(line)
		indent := len(line) - len(strings.TrimLeft(line, " "))
		if indent == 0 && trimmed == "tasks:" {
			inTasks = true
			continue
		}
		if !inTasks || trimmed == "" || strings.HasPrefix(trimmed, "#") {
			continue
		}
		if indent == 2 && strings.HasSuffix(trimmed, ":") {
			current = strings.TrimSuffix(trimmed, ":")
			tasks[current] = ""
			continue
		}
		if current != "" && indent == 4 && strings.HasPrefix(trimmed, "desc:") {
			tasks[current] = strings.Trim(strings.TrimSpace(strings.TrimPrefix(trimmed, "desc:")), `"'`)
		}
	}
	return tasks, scanner.Err()
}
