package main

import (
	"bufio"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

func automationCheck(root string, out io.Writer) error {
	requiredDocs := map[string][]string{
		"AGENTS.md": {
			"task doctor",
			"共享工作樹、單一 Writer",
			"generated files 禁止手改",
			"Go generated router 不擁有 AuthZ",
			"docs/development/automation.md",
		},
		filepath.Join("docs", "development", "automation.md"): {
			".devctl/**",
			"task gen:check",
			"SubAgent 預設唯讀",
			"不切 branch",
		},
	}
	var problems []string
	for relative, needles := range requiredDocs {
		data, err := os.ReadFile(filepath.Join(root, relative))
		if err != nil {
			problems = append(problems, fmt.Sprintf("%s: %v", relative, err))
			continue
		}
		text := string(data)
		for _, needle := range needles {
			if !strings.Contains(text, needle) {
				problems = append(problems, fmt.Sprintf("%s: missing %q", relative, needle))
			}
		}
	}

	tasks, err := taskDescriptions(filepath.Join(root, "Taskfile.yml"))
	if err != nil {
		return err
	}
	for name, description := range tasks {
		if strings.TrimSpace(description) == "" {
			problems = append(problems, fmt.Sprintf("Taskfile.yml: task %s has no desc", name))
		}
	}
	for _, name := range []string{"doctor", "bootstrap", "env:init", "gen", "gen:check", "ci"} {
		if _, ok := tasks[name]; !ok {
			problems = append(problems, fmt.Sprintf("Taskfile.yml: missing discoverable task %s", name))
		}
	}

	generatedMarkers := map[string]string{
		filepath.Join("apps", "platform", "internal", "foundation", "persistence", "db", "gen", "db.go"): "Code generated by sqlc",
		filepath.Join("apps", "platform", "internal", "entrypoint", "api", "gen", "oas_server_gen.go"): "Code generated by ogen",
		filepath.Join("packages", "api-client-ts", "src", "generated", "runtime.ts"):                   "auto generated by OpenAPI Generator",
		filepath.Join("packages", "api-stub-py", "src", "skillhub_api_stub", "generated", "models.py"): "generated by datamodel-codegen",
	}
	for relative, marker := range generatedMarkers {
		data, err := os.ReadFile(filepath.Join(root, relative))
		if err != nil {
			problems = append(problems, fmt.Sprintf("%s: %v", relative, err))
			continue
		}
		if !strings.Contains(string(data), marker) {
			problems = append(problems, fmt.Sprintf("%s: missing generated ownership marker %q", relative, marker))
		}
	}

	problems = append(problems, driftMarkerProblems(root)...)
	problems = append(problems, queryOwnerProblems(root)...)
	problems = append(problems, contextMapProblems(root)...)

	if len(problems) > 0 {
		for _, problem := range problems {
			fmt.Fprintln(out, "FAIL", problem)
		}
		return errors.New("developer automation contract is incomplete")
	}
	fmt.Fprintf(out, "automation contract: %d tasks documented; agent and generated ownership checks passed\n", len(tasks))
	return nil
}

// ADR-032 appendix A is the human-readable cross-context import whitelist and
// apps/platform/.golangci.yml holds its depguard equivalent. Tolerated drifts
// are tagged `drift: DDD-00x` in both, so the two multisets of markers must
// match exactly; a divergence means one side was edited alone.
//
// `\b` keeps the ADR's own placeholder text (`# drift: DDD-00x`) out of the
// count — a marker always ends at a non-word character.
var driftMarkerPattern = regexp.MustCompile(`drift: DDD-\d+\b`)

func driftMarkerProblems(root string) []string {
	sources := map[string]string{
		"lint": filepath.Join("apps", "platform", ".golangci.yml"),
		"adr":  filepath.Join("docs", "adr", "ADR-032-ddd-bounded-context-governance-for-platform.md"),
	}
	counts := map[string]map[string]int{}
	var problems []string
	for side, relative := range sources {
		data, err := os.ReadFile(filepath.Join(root, relative))
		if err != nil {
			return append(problems, fmt.Sprintf("%s: %v", relative, err))
		}
		counts[side] = map[string]int{}
		for _, marker := range driftMarkerPattern.FindAllString(string(data), -1) {
			counts[side][marker]++
		}
	}

	markers := map[string]bool{}
	for _, side := range counts {
		for marker := range side {
			markers[marker] = true
		}
	}
	var sorted []string
	for marker := range markers {
		sorted = append(sorted, marker)
	}
	sort.Strings(sorted)

	var differences []string
	for _, marker := range sorted {
		lint, adr := counts["lint"][marker], counts["adr"][marker]
		if lint != adr {
			differences = append(differences, fmt.Sprintf("%q lint=%d adr=%d", marker, lint, adr))
		}
	}
	if len(differences) > 0 {
		problems = append(problems, fmt.Sprintf(
			"%s and %s disagree on drift markers: %s",
			sources["lint"], sources["adr"], strings.Join(differences, "; ")))
	}
	return problems
}

func taskDescriptions(path string) (map[string]string, error) {
	file, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer file.Close()

	tasks := map[string]string{}
	inTasks := false
	current := ""
	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := scanner.Text()
		trimmed := strings.TrimSpace(line)
		indent := len(line) - len(strings.TrimLeft(line, " "))
		if indent == 0 && trimmed == "tasks:" {
			inTasks = true
			continue
		}
		if !inTasks || trimmed == "" || strings.HasPrefix(trimmed, "#") {
			continue
		}
		if indent == 2 && strings.HasSuffix(trimmed, ":") {
			current = strings.TrimSuffix(trimmed, ":")
			tasks[current] = ""
			continue
		}
		if current != "" && indent == 4 && strings.HasPrefix(trimmed, "desc:") {
			tasks[current] = strings.Trim(strings.TrimSpace(strings.TrimPrefix(trimmed, "desc:")), `"'`)
		}
	}
	return tasks, scanner.Err()
}
