package main

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestCommentBudget(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	write := func(relative, contents string) {
		path := filepath.Join(root, filepath.FromSlash(relative))
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(contents), 0o600); err != nil {
			t.Fatal(err)
		}
	}
	const fourLines = "// one\n// two\n// three\n// four\nfunc f() {}\n"

	write("apps/short.go", "package x\n\n// one\n// two\n// three\n//go:generate x\nfunc f() {}\n\n// Hashes with SHA-256.\nfunc g() {}\n")
	write("apps/deref.go", "package x\n\nfunc f(p *int) {\n\t*p = 1\n\t*p = 2\n\t*p = 3\n\t*p = 4\n}\n")
	write("apps/web/a.ts", "/**\n * one\n * two\n * three\n */\nexport const a = 1\n")
	write("apps/gen/db.go", "// Code generated by sqlc. DO NOT EDIT.\n"+fourLines)
	write("db/queries/q.sql", "-- name: GetUser :one\n-- one\n-- two\n-- three\nSELECT 1;\n")
	write("Taskfile.yml", "# one\n# two\n# three\ntasks: {}\n")
	if problems := commentBudgetProblems(root); len(problems) != 0 {
		t.Fatalf("a tree within the rule was refused: %v", problems)
	}

	write("apps/new.py", "# one\n# two\n# three\n# four\nx = 1\n")
	write("apps/doc.go", "// Package x one\n// two\n// three\n// four\npackage x\n")
	write("infra/Dockerfile", "# Decided in R-74.\nFROM scratch\n")
	write("apps/old.go", "package x\n\n"+fourLines+"\n"+fourLines)
	report := strings.Join(commentBudgetProblems(root), "\n")
	for _, want := range []string{"apps/doc.go has 1", "apps/new.py has 1", "apps/old.go has 2", "infra/Dockerfile has 1"} {
		if !strings.Contains(report, want) {
			t.Fatalf("missing %q in:\n%s", want, report)
		}
	}
	var lint bytes.Buffer
	if err := commentLint(root, []string{"infra/"}, &lint); err == nil || !strings.Contains(lint.String(), "infra/Dockerfile:1: work log") {
		t.Fatalf("comment-lint did not report the work log line: %q", lint.String())
	}
}
