package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func writeGoFile(t *testing.T, root, relative, body string) {
	t.Helper()
	path := filepath.Join(root, filepath.FromSlash(relative))
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
}

func writeFakeGenPackage(t *testing.T, root string) {
	t.Helper()
	writeGoFile(t, root, genDirRelative+"/fake.sql.go", `// Code generated by sqlc. DO NOT EDIT.
package gen

import "context"

type Queries struct{}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	return User{}, nil
}
func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	return User{}, nil
}
func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	return nil
}

type CreateUserParams struct{ Email string }
type User struct{ ID int64 }
`)
}

func TestSecondDataLayerProblemsFlagsThreeMatchingMethods(t *testing.T) {
	root := t.TempDir()
	writeFakeGenPackage(t, root)

	writeGoFile(t, root, "apps/platform/internal/fake/mem.go", `package fake

import (
	"context"

	"example.com/skillhub/apps/platform/internal/foundation/persistence/db/gen"
)

type memQueries struct{}

func (m *memQueries) CreateUser(ctx context.Context, arg gen.CreateUserParams) (gen.User, error) {
	return gen.User{}, nil
}
func (m *memQueries) GetUser(ctx context.Context, id int64) (gen.User, error) {
	return gen.User{}, nil
}
func (m *memQueries) DeleteUser(ctx context.Context, id int64) error {
	return nil
}
`)

	problems := secondDataLayerProblems(root)
	if len(problems) != 1 {
		t.Fatalf("got %d problems, want 1: %#v", len(problems), problems)
	}
	for _, want := range []string{"memQueries", "CreateUser", "GetUser", "DeleteUser", "PORT-008"} {
		if !strings.Contains(problems[0], want) {
			t.Errorf("problem missing %q: %s", want, problems[0])
		}
	}
}

func TestSecondDataLayerProblemsIgnoresTwoMatchingMethods(t *testing.T) {
	root := t.TempDir()
	writeFakeGenPackage(t, root)

	writeGoFile(t, root, "apps/platform/internal/fake/mem.go", `package fake

import (
	"context"

	"example.com/skillhub/apps/platform/internal/foundation/persistence/db/gen"
)

type memQueries struct{}

func (m *memQueries) CreateUser(ctx context.Context, arg gen.CreateUserParams) (gen.User, error) {
	return gen.User{}, nil
}
func (m *memQueries) GetUser(ctx context.Context, id int64) (gen.User, error) {
	return gen.User{}, nil
}
`)

	if problems := secondDataLayerProblems(root); len(problems) != 0 {
		t.Fatalf("two matches should be below the threshold: %#v", problems)
	}
}

func TestSecondDataLayerProblemsRequiresSignatureNotJustName(t *testing.T) {
	root := t.TempDir()
	writeFakeGenPackage(t, root)

	writeGoFile(t, root, "apps/platform/internal/fake/service.go", `package fake

import "context"

type workspace struct{}

type Service struct{}

func (s *Service) CreateUser(ctx context.Context, ws workspace, email string) (int64, error) {
	return 0, nil
}
func (s *Service) GetUser(ctx context.Context, ws workspace, id int64) (int64, error) {
	return 0, nil
}
func (s *Service) DeleteUser(ctx context.Context, ws workspace, id int64) error {
	return nil
}
`)

	if problems := secondDataLayerProblems(root); len(problems) != 0 {
		t.Fatalf("matching names with a different signature must not be flagged: %#v", problems)
	}
}

func TestSecondDataLayerProblemsReadsCodeNotComments(t *testing.T) {
	root := t.TempDir()
	writeFakeGenPackage(t, root)
	writeGoFile(t, root, "apps/platform/internal/fake/mem.go", `package fake

// type memQueries struct{}
//
// func (m *memQueries) CreateUser(ctx context.Context, arg gen.CreateUserParams) (gen.User, error) {
// 	return gen.User{}, nil
// }
// func (m *memQueries) GetUser(ctx context.Context, id int64) (gen.User, error) {
// 	return gen.User{}, nil
// }
// func (m *memQueries) DeleteUser(ctx context.Context, id int64) error {
// 	return nil
// }
`)

	if problems := secondDataLayerProblems(root); len(problems) != 0 {
		t.Fatalf("methods that exist only in a comment must not be flagged: %#v", problems)
	}
}

func TestSecondDataLayerProblemsIgnoresGenItself(t *testing.T) {
	root := t.TempDir()
	writeFakeGenPackage(t, root)

	if problems := secondDataLayerProblems(root); len(problems) != 0 {
		t.Fatalf("db/gen was flagged as a second copy of itself: %#v", problems)
	}
}

func TestTheRealRepositoryHasNoSecondDataLayer(t *testing.T) {
	root, err := findRepoRoot()
	if err != nil {
		t.Skipf("not inside the repository: %v", err)
	}
	sigs, err := genMethodSignatures(root)
	if err != nil {
		t.Fatal(err)
	}
	if len(sigs) < 100 {
		t.Fatalf("found only %d db/gen methods; the scan is probably looking in the wrong place", len(sigs))
	}
	if got, want := sigs["CreateUser"], "func(Context, CreateUserParams) (User, error)"; got != want {
		t.Errorf("CreateUser normalized signature = %q, want %q", got, want)
	}
	if problems := secondDataLayerProblems(root); len(problems) != 0 {
		t.Errorf("02:PORT-008 violation(s) found in the real tree: %#v", problems)
	}
}
