line-length = 100

[lint]
select = ["C90", "PLR", "SIM", "B", "RET", "ARG", "PLW", "PERF", "N", "FBT", "C4", "PIE"]

[lint.per-file-ignores]
"test_*.py" = ["PLR", "SIM", "B", "RET", "ARG", "PLW", "PERF", "N", "FBT", "C4", "PIE"]

[lint.mccabe]
max-complexity = 10

[lint.pylint]
max-branches = 12
max-statements = 50
